### PR TITLE
Use Alpine latest version

### PR DESCRIPTION
**Pull request by trung**
First, thanks for the awesome automation on this.

Currently it's `3.6`. Is there a reason not to use latest Alpine?

### CODE REVIEW

**Comment by jones2026** [comment]
Any thoughts on just enabling renovate or dependabot on this repo to keep the version always up to date?

**Comment by mauricios** [comment]
@vincetse Any chance that you can review this PR?

**Comment by trung** [comment]
Latest Docker file now points to `alpine:latest` so we are good.
The most recent image has:
```
› docker image inspect infrastructureascode/aws-cli:latest
[
    {
        "Id": "sha256:7df6a5bdf89072a1a8152ee3216054cb428f9de4c63a6e50ef9402428eff156f",
        "RepoTags": [
            "infrastructureascode/aws-cli:latest"
        ],
        "RepoDigests": [
            "infrastructureascode/aws-cli@sha256:f53fd6c2afa3cbec4222994123dcd199b4635e5258b796d77c3b49a663f5f40e"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2019-12-24T12:44:31.182652668Z",
        "Container": "c85aa96f2529e58c1ea1dbd8358b5663b5435ffcc8a3627ed58445b597fc1bc2",
        "ContainerConfig": {
            "Hostname": "c85aa96f2529",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "AWSCLI_VERSION=1.16.309"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) WORKDIR /project"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:bef0c6db3a31c44680eb67a3efddb9ee022c68222c8533335e0594302dab9457",
            "Volumes": {
                "/project": {},
                "/root/.aws": {}
            },
            "WorkingDir": "/project",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "DockerVersion": "18.03.1-ee-3",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "AWSCLI_VERSION=1.16.309"
            ],
            "Cmd": [
                "/bin/sh"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:bef0c6db3a31c44680eb67a3efddb9ee022c68222c8533335e0594302dab9457",
            "Volumes": {
                "/project": {},
                "/root/.aws": {}
            },
            "WorkingDir": "/project",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 119596782,
        "VirtualSize": 119596782,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/49df5e074332638f9b428a992c637383d6b6011cd0c0e3ac08ed9bc115a1bf0b/diff:/var/lib/docker/overlay2/e34bbd1924a9dbd49608b4f5d433352a2a694a83a147fa06549a00ed3dba86e3/diff",
                "MergedDir": "/var/lib/docker/overlay2/96c8ceb2d139d65872612c6a25b3bad62343355e86ef8166fc9ad7fbce229c94/merged",
                "UpperDir": "/var/lib/docker/overlay2/96c8ceb2d139d65872612c6a25b3bad62343355e86ef8166fc9ad7fbce229c94/diff",
                "WorkDir": "/var/lib/docker/overlay2/96c8ceb2d139d65872612c6a25b3bad62343355e86ef8166fc9ad7fbce229c94/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:721384ec99e56bc06202a738722bcb4b8254b9bbd71c43ab7ad0d9e773ced7ac",
                "sha256:841518e894db557f9af6aa5ee9ed5d1c777889c04b8b425ec7d191e012823c32",
                "sha256:4afcf1f3f3d3bccbe9b01d0ea0c8dc70991b5771af477bf6e639c03c0fe57409"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
› docker run --rm -it infrastructureascode/aws-cli:latest /bin/sh
/project # uname -a
Linux 892e36ea5213 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 Linux
/project # cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.6.5
PRETTY_NAME="Alpine Linux v3.6"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```

**Comment by vincetse** [comment]
@trung & @mauricios:
My apologies on the delay here.  I'd be happy to merge this one quickly if you reopen the PR.

**Comment by trung** [comment]
@vincetse  a bit oversight from me. Reopened

**Comment by vincetse** [comment]
> First, thanks for the awesome automation on this.
> 
> Currently it's `3.6`. Is there a reason not to use latest Alpine?

Just merged the PR, and apologies for not getting to this for more than a year!  I fell asleep at the wheel since the automation basically self-updated this thing.

**Pull request merged**
